FROM kelseyhightower/golang-musl:1.4.2
MAINTAINER Kelsey Hightower <kelsey.hightower@gmail.com>

RUN mkdir -p /go/src/github.com/GoogleCloudPlatform/kubernetes
WORKDIR /go/src/github.com/GoogleCloudPlatform/kubernetes
